CREATE DATABASE galvanize_contracts;

CREATE USER galvanize_admin PASSWORD 'galvanize_P@$$w0rd';

REVOKE ALL PRIVILEGES ON DATABASE galvanize_contracts FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO PUBLIC;

ALTER USER galvanize_admin WITH SUPERUSER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO galvanize_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO galvanize_admin;
